theme: cayman
title: [Steven Haynes]
description: [I am an aspiring software engineer seeking to do excellent work that challenges me and keeps me inspired while also making other people's lives easier.]
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
